- cdk.context.json
- config/Config.ts
- config/config.json
- lib/finch-pipeline-app-stage.ts
- lib/finch-pipeline-stack.ts
Separate release infrastructure and CI infrastructure.
Create a new release account and corresponding runner stack.
> Add release account and create runner stack

- cdk.context.json
- config/Config.ts
- config/config.json
- lib/finch-pipeline-app-stage.ts
- lib/finch-pipeline-stack.ts
Need to separate runners between CI and release.
Added a new release account and create runners for it.
> Add new release accounts and corresponding runners

- lib/asg-runner-stack.ts
This will no longer allow maintainers to SSH to runners to troubleshoot issues
> Restricts runner security group

- config/runner-config.json
> fix: incorrect beta Windows license ARN

- bin/finch-aws-cdk.ts
N/A
Adds termination protection to the Finch pipeline stack
> Enable termination protection on pipeline stack

- config/runner-config.ts
- lib/finch-pipeline-app-stage.ts
- lib/ssm-patching-stack.ts
- test/artifact-bucket-cloudfront.test.ts
- test/cloudfront_cdn.test.ts
- test/ecr-repo-stack.test.ts
- test/event-bridge-scan-notifs-stack.test.ts
- test/finch-pipeline-stack.test.ts
- test/ssm-patching-stack.test.ts
- Adds SSM patching stack
- Formatted a few files
- unit tests
- tested on local deployment
> feat: add ssm patching stack

- lib/finch-pipeline-app-stage.ts
N/A
Adds termination protection to stacks defined by FinchPipelineAppStage
> Add termination proection to pipeline stage

- scripts/setup-linux-runner.sh
Signed-off-by: jingwei wang <jweiw@amazon.com>
add node v-22.9.0 to AL2 set up runner
add node v-22.9.0 to AL2 set up runner
run added command in a ec2 AL2 instance
> add node v-22.9.0 in AL2 runner script

- scripts/windows-runner-user-data.yaml
add aws CLI in windows runner
- [ x] I've reviewed the guidance in CONTRIBUTING.md
> feat: add aws CLI in windows runner

- scripts/setup-linux-runner.sh
- We changed the version in #833, but didn't update the hashes. This should fix that.
> ci: fix GHA runner archive hashes

- scripts/setup-linux-runner.sh
- The previous attempt to downgrade the listener failed because the "last working version" that we hardcoded was too old to connect to GitHub:
```
An error occured: Runner version v2.320.0 is deprecated and cannot receive messages.
```
- This new workaround pins the listener script to a pre-determiend (and controlled by us) version of node. At some point in the future, it might break, due to changes in GitHub's file, or because we need to pin to a newer version of node.
- Executed the new script on AL2 instances (both arches)
> ci: patch GitHub runner's runsvc.sh to use system node for the listener

- scripts/setup-linux-runner.sh
- Replace the bundled node version with a symlink to the system node version
> ci: replace bundled node binaries with symlink to system node

- scripts/setup-linux-runner.sh
Previously, the systemd service was configured to be a oneshot, but this is wrong because the service should be long lived.
Also, on AL2, the inotify-tools package is only available via the epel repo, so we need to enable that.
> ci: fix watcher systemd service

- lib/codebuild-stack.ts
- test/codebuild-stack.test.ts
- Add EC2 service roles to Codebuild fleet
`npm run test`
> fix: add fleet service role

- lib/codebuild-stack.ts
- lib/finch-pipeline-app-stage.ts
- lib/utils.ts
- test/codebuild-stack.test.ts
- test/utils.test.ts
- Add `environmentType` and `buildImageOS` to `CodeBuildStackArgs` for extensibility.
`npm run test`
> fix: use arm ec2 instance

- lib/codebuild-stack.ts
- add GH creds to Codebuild stacj
`npm run test`
> fix: add github creds to codebuild stack

- lib/finch-pipeline-app-stage.ts
> fix: add dependency between creds and codeBuildStack

- scripts/windows-runner-user-data.yaml
Updated WSL version to [2.4.13](https://github.com/microsoft/WSL/releases/tag/2.4.13)
> chore: update WSL to version 2.4.13

- lib/finch-pipeline-app-stage.ts
- Add pipeline stage to codebuild project name
- `npm run test`
> fix: codebuild project name includes pipeline stage

- lib/codebuild-stack.ts
- lib/finch-pipeline-app-stage.ts
- lib/utils.ts
- package-lock.json
- package.json
- test/codebuild-stack.test.ts
- undo previous revert https://github.com/runfinch/infrastructure/pull/984
> feat: add mac instances in codebuild project

- lib/utils.ts
*Description of changes:* Adding more CodeBuild runners for automated SAMcli testing. We are trying 5, but this might be over the limit.
*Testing done:* The notification from the pipeline will tell us whether or not this amount is allowed, and we can adjust accordingly.
> ci: more arm runners
