runfinch/infrastructure

lib/finch-pipeline-app-stage.ts
lib/mac-runner-stack.ts
lib/pvre-reporting-stack.ts
lib/pvre-reporting-template.yml
package-lock.json
package.json

To monitor the OS patching, The Mac Instances needs to report to PVRE. This changes will allow the Mac Instances to report the OS versions to PVRE for generating the report.
Yes. In local dev account.

PVRE reporting using SSM for Mac Instances in beta-infra

---

lib/finch-pipeline-app-stage.ts
lib/mac-runner-stack.ts

N/A
To monitor the OS patching, The Mac Instances needs to report to PVRE. This changes will allow the Prod Mac Instances to report the OS versions to PVRE for generating the report.
Yes. In local dev account.

Enable PVRE Reporting for All Mac Instances

---

cdk.context.json
config/Config.ts
config/config.json
lib/finch-pipeline-app-stage.ts
lib/finch-pipeline-stack.ts

This reverts [commit c3a8c25462c7556845d833bb2702e8750900f818](https://github.com/runfinch/infrastructure/commit/c3a8c25462c7556845d833bb2702e8750900f818).
- Current release account does not have the service quota needed to start the macOS instances, so that commit is rolled back to enable the subsequent commit for enabling [PVRE monitoring](https://github.com/runfinch/infrastructure/commit/ee4995357f2bc688e1a70e585d90801858d009a5) to work.
- Ran `cdk synth` locally

Revert "Add release account and create runner stack (#144)"

---

cdk.context.json
lib/finch-pipeline-app-stage.ts
lib/setup-amd64-runner.sh
lib/setup-arm64-runner.sh

- https://github.com/runfinch/infrastructure/issues/40
- Onboard four more macOS 13.2 runners to eventually replace the macOS 11.7 runners.
- Updated the runner provisioning script for the newest GH Actions app
- Ran `cdk synth` locally
- Ran `npm test` locally

Updated prod stage for 4 more ventura runners

---

lib/setup-amd64-runner.sh
lib/setup-arm64-runner.sh

Updated GH Action runner data files for https://github.com/runfinch/infrastructure/commit/bc9ac2e20bc1592c3c73d05316a632efa51d7076 caused instances to restart and time out due to the long waiting period for macOS instances.
- Reverted data file changes.

Revert data files to prevent mac instances restarting

---

lib/finch-pipeline-app-stage.ts

Previously, the default value of availability zone was hardcoded to `west-us2`. This was preventing us to deploy mac instances for other regions such as `east-us2` for release infra. To support multi region, this PR made two changes:
1. Instead of hardcoding the default availability zone to `west-us2`, now we can pass it as part of mac config parameter for each instance.
2. To select the availability zone from the cdk context, previously it used to select the 4th elements from the availabilityzone list. But not all region has 4 or more availability zone. To fix this this PR selects the last availability zone from the list instead.
I have tested this code by running `cdk synth` in local computer.
By submitting this pull …

Multi Region AvailabilityZone selection of mac instances

---

lib/finch-pipeline-app-stage.ts

macOS 13 instances were removed from the pipeline in https://github.com/runfinch/infrastructure/pull/182, this PR adds them back.
Ran cdk synth and npm test.

Add prod ventura instances again

---

package-lock.json
package.json

Reverts runfinch/infrastructure#183 as node-fetch version above 3.2.9 has a bunch of Typescript type errors:
https://github.com/node-fetch/node-fetch/issues/1617

Revert "build(deps): bump node-fetch from 2.6.7 to 3.3.1"

---

scripts/setup-runner.sh

*Issue #, if available:* [runfinch/finch #395](https://github.com/runfinch/finch/pull/395)
- Add brew path to `/Users/ec2-user/.zshenv`
- The current mechanism of configuring brew is done in ~/.zshrc by default. ~/.zshrc only gets loaded in interactive sessions. CI does not run in an interactive session, hence the `brew not found` errors we're seeing in CI. On amd64 macs, the install path of brew is in a standard location, but on amd64 (M1) macs, this isn't the case. `~/.zshenv` is always loaded, so `brew` should be in `PATH` when CI runs.
- locally modified `~/.zshenv` on some CI hosts

fix: brew path

---

config/runner-config.json

macOS 12 default xcode version doesn't meet the requirement to build nerdctl. Update release runner to macOS 13 for nerdctl build, while preserve macOS 11 to support other executables collection.

ci: Change finch-core release runner from os 12 to 13

---

lib/asg-runner-stack.ts

Updated the updatepolicy on our ASGs so that when the following operations are performed, the instances are refreshed automatically.
- Change the Auto Scaling group's [AWS::AutoScaling::LaunchConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html).
- Change the Auto Scaling group's VPCZoneIdentifier property.
- Change the Auto Scaling group's LaunchTemplate property.
- Update an Auto Scaling group that contains instances that don't match the current LaunchConfiguration.

Update instance updatepolicy

---

scripts/setup-runner.sh

Tests / installer generation workflows failed on M1 after the fleet got refreshed. Checks the instance logs, and it looks like its because whatever user runs the setup script has `$HOME` set to "". Using `$HOMEDIR` instead should fix the issue. Will trigger and require redeployment to fix.
- Manually re-configured `.zshenv` on one host.

fix: use $HOMEDIR instead of $HOME

---

lib/asg-runner-stack.ts

*Issue:*
- Pipeline fails as it waits for a signal that is never defined
- Explicitly defining defaults for UpdatePolicy RollingUpdate does not take into account some checks performed
- Turned off `waitOnResourceSignals` as we do not have any resource signals defined for the ASG.
- Not 100% sure how to test this change. What are others thoughts?

fix: remove wait on resource signal on updates

---

lib/continuous-integration-stack.ts
lib/ecr-repo-stack.ts
lib/finch-pipeline-app-stage.ts
test/ecr-repo-stack.test.ts

https://github.com/runfinch/finch/issues/492
Add an ECR repo to Finch infrastructure. this repository is where the image used as the basis for the Finch VM rootfs will live.
Context: To support Finch on Windows, we will be using WSL2. WSL2 differs from the Finch on Mac qemu/vz implementation in that WSL2 provides a kernel and requires just a root filesystem to boot a custom distribution. We will be maintaining the root filesystem as an image in this ECR repository. Subsequent PRs to finch-core will include the Dockerfile, actions for exporting the image as an archive and uploading to the Finch dependencies S3 bucket.
For now, the ECR repository is private to limit access controls to the GitHub action responsible for interacting with the …

add ECR repo for finch rootfs image

---

lib/continuous-integration-stack.ts

Need to give permissions for the GitHub Actions role to read the ECR authorization token such that it can auth to push and pull from the repo.

fix: add ecr auth to GitHub Actions role

---

.github/workflows/ci.yaml
package-lock.json
package.json

N/A
This reverts commit da35ca94230a63bc9c17a8e453a90814540248bc.
The node-fetch dependency update is causing some issues in the backend AWS CodePipeline for Finch infrastructure. Revert the dependency update to unblock pipeline and have follow-up action items for addressing gaps between dependency update workflows and backend pipeline.

Revert "build(deps): bump node-fetch from 2.6.7 to 3.3.2 (#359)"

---

config/runner-config.json
config/runner-config.ts
lib/asg-runner-stack.ts
lib/finch-pipeline-app-stage.ts
scripts/windows-runner-user-data.yaml

* change RunnerType to include platform
* refactor asg-runner-stack to build for both platform types macOS and
windows
* add windows-runner-user-data.yaml with PowerShell script to set up
runner
* update runner-config.json to include Windows runners for beta, prod, and release
* add licenses for Windows
* refactor to define 'windows' and 'mac' as a `PlatformType` `enum`
`windows-runner-user-data.yaml` is a User Script for launching a Windows EC2 instance that:
- logs to C:\UserData.log
- installs winget, git, Make, AWS tools, and latest powershell
- installs WSL2 and its dependencies
* reboots the instance to apply the installation
- periodically updates WSL2
- registers as a self-hosted GitHub Actions runner on instance startup
*Testing …

feat: add windows runner instances

---

scripts/windows-runner-user-data.yaml

By default, the GitHub actions runner will run as the NetworkService account.
The GitHub Actions runner user is the [NetworkService Account](https://learn.microsoft.com/en-us/windows/win32/services/networkservice-account?redirectedfrom=MSDN). This account does not have administrator privileges: https://github.com/ginglis13/finch/actions/runs/6303042315/job/17111485195?pr=1
```
Run whoami
whoami
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
$currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
NETWORK SERVICE
False
``` …

fix: give the actions runner service system privileges

---

scripts/windows-runner-user-data.yaml

GitHub Actions connect to runners via session 0 / ssh. In versions of WSL installed from the Windows store (wsl --install), wsl cannot be invoked via connections over session 0. The pre-release version of WSL has patches to accommodate this, so install that version instead of the version provided by the Windows store.
related: https://github.com/microsoft/WSL/issues/9231
Manually instance setup with minimal user data script:
```yaml
version: 1.0
tasks:
- task: executeScript
inputs:
- frequency: once
type: powershell
runAs: admin
content: |-
wsl --install --no-distribution
$startupscript = @'
Start-Transcript -Path "C:\StartupScript.log" -Append
Invoke-WebRequest -Uri …
```

fix: use pre-release version of WSL

---

scripts/windows-runner-user-data.yaml

Previously, the GitHub Actions runner service was running under a local system account that did that have full permissions to run wsl. Change ownership of the service to the local Administrator account so all wsl commands will work as expected.

fix: runs GHA service on Windows as Administrator

---

lib/asg-runner-stack.ts

While {mac1,mac2}.metal instances default to a size of 100GiB for their respective root volumes on EC2, m5zn.metal instances default to a size of 30GiB for the root volume. Specify explicit size to keep consistency between the two platforms and to avoid potential issues with storage limits hit.
See https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.LaunchTemplate.html#construct-props and https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.BlockDevice.html
`/dev/sda1` is a placeholder name for the root volume on both macOS and Windows EC2 instances
`npm run cdk synth`

fix: increase size of root volume for runners

---

scripts/windows-runner-user-data.yaml

The GitHub Actions Runner service is configured to be logged in as the Administrator user such that the service has correct permissions to interact with WSL. Previously, when the service started on instance reboot, it would fail because the Administrator user is not in the set of users granted permissions to "Log on As Service". Fix by using 'Carbon' powershell module (https://get-carbon.org/Grant-Privilege.html) that grants the Administrator user proper rights.
See also: https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc794944(v=ws.10)?redirectedfrom=MSDN#to-add-the-log-on-as-a-service-right-to-an-account-on-your-local-computer
Also added some extra logging and use `GH_KEY` as Admin …

fix: give Administrator log on as service rights

---

scripts/windows-runner-user-data.yaml

instances `setup7.ps1` script was failing due to
https://cdn.winget.microsoft.com/cache/source.msix being down when
manually updating package cache sources. To mitigate, remove our
dependency on winget and install from source.
See also https://github.com/microsoft/winget-cli/issues/3652
dev ec2 instance, confirmed install of `git` and `make`.

deps: remove winget, download exes

---

lib/event-bridge-scan-notifs-stack.ts
lib/finch-pipeline-app-stage.ts
lib/image-scanning-notifications-lambda-handler/main.py
test/event-bridge-scan-notifs-stack.test.ts

Closes #357
Amazon ECR offers Enhanced Image Scanning, which we have enabled for the rootfs image used for Finch on Windows. This change implements a stack to automatically notify Finch developers of scan results when the finding is HIGH or CRITICAL in severity (aka CVE score >= 7.0).
An SNS topic is created for the notification, and a Lambda function is wired to EventBridge to listen for events from AWS Inspector of those severities.
Manually deployment and verification of notification email. Emails received from `AWS Notifications <no-reply@sns.amazonaws.com>`. Example text below:
```text
Rootfs Image Security Finding
Severity: HIGH
Type: PACKAGE_VULNERABILITY
Description: Use After Free in GitHub repository vim/vim …
```

feat: add rootfs image scanning notifications

---

scripts/windows-runner-user-data.yaml

PR #441 added a firewall rule to allow inbound traffic to the WSL VM. However, no WSL VM is started in this startup script, so no interfaces were available to provide to the rule. CI changes in the main Finch repo were taking care of launching a Ubuntu distro. Better practice would be to install that distro in the init script of the runner itself.

fix: install Ubuntu WSL distro in startup script

---

config/runner-config.json

Currently only have one windows CI runner in finch repo, which stack a lot PRs.
For macOS, we have 2 instances per os & arch for CI purpose, add one more windows to keep them consistent and efficient.
Change the instance count to 2

ci: Add one more windows CI runner

---

lib/image-scanning-notifications-lambda-handler/main.py

The final rev of #403 included adding type hinting. Lambda func is not bundled with a layer that includes the aws_lambda_powertools python package. Since this package was only used for type hinting, and since those types are encapsulated in docstrings for relevant functions, remove the imports.

fix: remove type hints from unimported libs

---

lib/image-scanning-notifications-lambda-handler/main.py

`region` is not a valid keyword arg to the boto3.client API. fix to remove named parameter in order to default to the region the function is deployed in.
test invokes on lambda func

fix: use default boto3 client region

---

scripts/windows-runner-user-data.yaml

- WSL2 2.x preview versions before 2.0.4 have an error when upgrading to later versions. I believe this error was encountered on all runners, as they are now in a state where `wsl --list` fails 100% of the time. This change should refresh the fleet, causing the new runners to come up with a fixed version
- Update WSL version
- Remove components that aren't needed on the runners (Windows Terminal + dependencies)
- Tested on local machine

refactor: remove excess components and update WSL installer

---

scripts/windows-runner-user-data.yaml

NuGet is a Carbon dependency and we use Carbon to manipulate the GitHub Runner service. In the last PR, I removed it because it wasn't obvious why we needed it

fix: add NuGet back (Carbon dependency)

---

integration_test/cloudfront_service.test.ts
lib/finch-pipeline-stack.ts
package-lock.json
package.json
tsconfig.json

Before this change, node-fetch was causing `npm run integration` to fail with an error like:
```js
import http from 'node:http';
^^^^^^
SyntaxError: Cannot use import statement outside a module
import fetch from 'node-fetch';
^
describe('Integration test', () => {
test('200 Response from CloudFront Distribution', async () => {
const url = process.env.CLOUDFRONT_URL ? `https://${process.env.CLOUDFRONT_URL}/test.html` : 'No URL in env';
at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
at Object.<anonymous> (integration_test/cloudfront_service.test.ts:1:1)
```
- remove node-fetch and replace it with NodeJS's native fetch
- upgrade codebuild pipeline to use a newer version of nodejs, so native fetch is …

deps: upgrade pacakges and remove node-fetch

---

scripts/windows-runner-user-data.yaml

- Updated
- git version
- github runner version
- wsl version
- go version
- added yq (for this PR)
The large diff is because I also applied formatting. Ignoring whitespace when reviewing should help

build(windows): add yq and bump versions

---

lib/artifact-bucket-cloudfront.ts
lib/asg-runner-stack.ts
lib/aspects/stack-termination-protection.ts
lib/continuous-integration-stack.ts
lib/ecr-repo-stack.ts
lib/event-bridge-scan-notifs-stack.ts
lib/finch-pipeline-app-stage.ts
lib/finch-pipeline-stack.ts
lib/pvre-reporting-stack.ts
test/artifact-bucket-cloudfront.test.ts
test/asg-runner-stack.test.ts
test/aspects/stack-termination-protection.test.ts
test/ecr-repo-stack.test.ts
test/event-bridge-scan-notifs-stack.test.ts
test/finch-pipeline-stack.test.ts

It is recommended to enable termination protection for CloudFormation stacks. Finch infrastructure currently does this for FinchPipelineStack but not for all stacks.
This change enables termination protection on all CloudFormation stacks.
```
npm run test
```
Signed-off-by: Austin Vazquez <macedonv@amazon.com>

feat: enable termination protection on CloudFormation stacks

---

config/env-config.ts
config/runner-config.json
config/runner-config.ts
lib/asg-runner-stack.ts
lib/finch-pipeline-app-stage.ts
lib/finch-pipeline-stack.ts
scripts/setup-linux-runner.sh
test/asg-runner-stack.test.ts

Adding Linux e2e test runners In support of https://github.com/runfinch/finch/pull/1023
- Adds Amazon Linux 2 and 2023 runners
- Only added for finch repo for now, because there's no value in testing finch-core changes on Linux as they do not impact finch on linux functionality
- User data setup script configured in a way that makes it easy to extend support to other Linux varieties
- Unit tests
- Tested in my own stack

feat: add linux runners

---

lib/asg-runner-stack.ts

Stack deployment rolled back in Beta due to incorrect AMI cpuTypes on ARM (since it defaults to x86_64)

fix: specify cpuType in MachineImage AMI search

---

lib/asg-runner-stack.ts
lib/finch-pipeline-app-stage.ts
test/asg-runner-stack.test.ts

Been writing too much go and forgot that typescript switch/case statements fallthrough by default. We should consider changing our tscofing's `noFallthroughCasesInSwitch` setting separately

fix: switch/case statement fallthrough

---

lib/ssm-patching-stack.ts
test/ssm-patching-stack.test.ts

- Makes the patching more frequent (once a week to once a day)
- Allows 100% patching failure, since this is at worst a no-op, and not all hosts will support patching (e.g. macOS)

chore: make patching more frequent

---

config/runner-config.json

Currently, we are using macOS 11 runners to build this archive. macOS 11 is deprecated, and we are no longer able to install our dependencies, which is causing runs to fail. 
<details>
<summary>Error excerpt for https://github.com/runfinch/finch-core/actions/runs/11342859343/job/31544196556#step:5:174
</summary>
```
==> Installing qemu dependency: python-packaging
==> Downloading https://ghcr.io/v2/homebrew/core/python-packaging/manifests/24.1_1
Already downloaded: /Users/ec2-user/Library/Caches/Homebrew/downloads/0a8b3181cb4fa8bee143a75cd85f08eb834903bde31ef0a291f3fe9f82bdbe41--python-packaging-24.1_1.bottle_manifest.json
==> Pouring python-packaging--24.1_1.all.bottle.tar.gz
🍺  /opt/homebrew/Cellar/python-packaging/24.1_1: 74 files, 545.5KB
==> Installing qemu …
```

ci: add macOS 12 hosts for building finch-core lima archive

---

scripts/windows-runner-user-data.yaml

- Adds git.exe to PATH (it's in `C:\Program Files\Git\bin\`, but not `C:\Program Files\Git\usr\bin`)
- Bumps versions of a few dependencies (git for windows, yq, golang)

chore: bump deps and add git.exe to PATH

---

scripts/windows-runner-user-data.yaml

Fix cannot directly use aws cli in command line
have a windows instance and using windows app test the power shell command

fix: Add aws cli to system path

---

scripts/windows-runner-user-data.yaml

ci: fix aws cli environment variable

---

scripts/setup-linux-runner.sh

*Issue #, if available:* Amazon Linux 2 nodes are failing to register because they do not ship a compatible version of Node.
- Disables Linux self-hosted runner auto-updates on the last version which ships Node 16.

ci: disable Linux selfhosted GitHub runner autoupdates

---

scripts/setup-linux-runner.sh

- Remove erroneous `restorecon`
- restorecon was erroring out and is unnecessary for things in the `${RUNNERDIR}` since we already set context with `semanage` in the preceding lines:
```
ValueError: File context for /home/ec2-user/ar/runsvc.sh is not defined
```
- This was never realized before because we were not using `set -e` for this script
- This was causing the ec2 user data script to exit before running the GH runner `./svc.sh install` and `./svc.sh start` scripts
- The failure of the user-data script does not cause the instances to go into a failure state. We should add that as a followup (not sure how straightforward that is)
- Executed on runners
By submitting this pull request, I confirm that my contribution is …

ci: remove erroneous restorecon

---

scripts/setup-linux-runner.sh

- Fix for #870
- Previously tested that the find/remove/symlink logic worked, but didn't test that writing the script to the file worked. It did not, because the $ for $line needs to be escaped.
- Tested the cating to file logic, to make sure the full $line makes it to the end script

ci(fix): escape nested variable

---

scripts/windows-runner-user-data.yaml

*Issue #, if available:* https://github.com/runfinch/finch/actions/runs/13950287431/job/39048083043#step:14:45
> [github.com/runfinch/finch/e2e/vm.test](http://github.com/runfinch/finch/e2e/vm.test): open C:\Users\ADMINI~1\AppData\Local\Temp\go-build3463726325\b001\vm.test.exe: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
- Adds a Windows Defender exception for the temporary go test generated executables
- Manually ran command on host

ci: add defender exception

---

scripts/setup-linux-runner.sh

This change adds a file watcher to the runner setup script. It monitors the `$RUNNER_DIR` for all file changes. This cannot be scoped down to a more specific directory,  because `inotifywait` does not take a file glob itself, and the `externals` directory can be suffixed with version numbers (e.g. externals.someversion, not just one externals dir).
Having a file watcher which re-executes the node patching script handles cases where the GitHub Actions runner updates or installs new versions of node, but _does not_ re-trigger the systemd service (which previously was the only way the node versions were patched).
- Tested on local machine
By submitting this pull request, I confirm that my contribution is made under the terms …

ci: add file watcher script for node version patcher

---

.gitignore
lib/codebuild-stack.ts
lib/finch-pipeline-app-stage.ts
lib/utils.ts
test/codebuild-stack.test.ts
test/utils.test.ts
tsconfig.json

- Implemented a CodeBuild stack that supports Linux, Mac, and Windows AMI build images. 
- Added two Ubuntu CodeBuild stacks to the pipeline, one for each arch (`x86_64` and `arm64`)
`npm run test`

feat: codebuild stack

---

lib/codebuild-stack.ts

- Secret was improperly formatted, causing the pipeline to fail. CodeBuild just needed the secret name, not the ARN

fix: CodeBuild access token secret and update GitHub source fields

---

lib/codebuild-stack.ts
lib/finch-pipeline-app-stage.ts

CodeBuild credentials are account-wide, so creating them multiple times causes an error
- Moved CodeBuild credential creation outside of for loop

fix: CodeBuild secert multiple instantiation

---

lib/codebuild-stack.ts
lib/finch-pipeline-app-stage.ts

- Enable termination protection for the Codebuild fleet by setting the `DisableApiTermination` to true, as suggested by the [AWS Docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_ChangingDisableAPITermination.html)
`npm run test`

fix: enable termination protection for codebuild fleet

---

lib/codebuild-stack.ts
lib/finch-pipeline-app-stage.ts
lib/utils.ts
package-lock.json
package.json
test/codebuild-stack.test.ts

This PR adds changes to provison mac host codebuild runners for the finch-daemon project. 
This will 
- provision a fleet with 
- - *One* Apple M2 (8 vCPUs, 24GiB memory)
- create a codebuild project with github source as the runfinch/finch-daemon repository
- enable us to run finch-daemon tests within the finch vm on each new PR
- Updated codebuild-stack.tests.ts with appropriate tests

feat: add mac instances in codebuild project

---

lib/codebuild-stack.ts

Resolves IAM permission error during stack updates where the fleet service role couldn't access the GitHub access token secret needed for webhook operations.
- Deployed to personal account and ran two updates via cdk on the created stack

fix: Add SM permission to codebuild fleet service role

---

lib/finch-pipeline-app-stage.ts
lib/utils.ts

*Description of changes:* Allowing prod account 090529234398 to have access to 3 mac runners. It currently has access to 1 runner, which is able to be picked up through GitHub Actions (though is still showing some issues). 
*Testing done:* We do not know whether this account has a high enough c-score for this increase to be successful. This merge will show us whether this is possible, and we can act accordingly.

ci: increase mac runners under envProd account

---

config/runner-config.json

Macos 12 support for brew has been stopped. This was leading to patching errors.

chore: update mac os version
